### PR TITLE
Improve ignore logic performance.

### PR DESCRIPTION
**Pull request by stefanmaric**
Replacing the `glob`-generated list of files and `.indexOf` with
`minimatch` (which is already a dependency of `glob`) I'm getting
great performance boost for all test scenarios I tried in my local
setup, specially under the default `echint` behaviour.
Since there's no benchmarking in place, please someone try this
branch.

### CODE REVIEW

**Comment by stefanmaric** [comment]
See #67 for more info.

**Comment by stefanmaric** [comment]
Documentation has to be updated, to reflect these changes and also to remove some misinformation (e.g. that `-i *.md` would work (it needs to be quoted)).

**Comment by ahmadnassri** [comment]
thanks, reviewing and merging!

**Comment by stefanmaric** [comment]
@ahmadnassri any news on this and/or #69? Would really love to have these published to npm for production stuff. :heart: 

You told me you were doing some merges on your side, but I can update these PRs to resolve conflicts, you just let me know.

**Comment by ahmadnassri** [comment]
@stefanmaric apologies for the delay! competing priorities! I've added you as a collaborator, please feel free to make the necessary changes and I'll push to npm, my merge ended up being messy and my changes are deep (replacing commander with yargs and minimizing dependencies)

I'll have to turn those into feature branches and work on them separately.

**Comment by stefanmaric** [comment]
> I've added you as a collaborator, please feel free to make the necessary changes and I'll push to npm

Sweet yisus!

I accepted, but still will simply update these PRs for easy merge. :+1:

**Comment by ahmadnassri** [comment]
👍

**Pull request merged**
